/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.sql_usuarios;
import Modelo.usuarios;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ettkt
 */
public class vista_usuarios extends javax.swing.JFrame {

    /**
     * Creates new form vista_usuarios
     */
    public vista_usuarios() {

        initComponents();
        setLocationRelativeTo(null);

        sql_usuarios sqlusr = new sql_usuarios();

        if (sqlusr.cargar(this)) {
        }

        if (sqlusr.cargarTiposUsuarios(this)) {
        }

        if (sqlusr.cargarStatusUsuarios(this)) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTusuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        txtUsuarioU = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApU = new javax.swing.JTextField();
        txtNombreU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAmU = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCorreoU = new javax.swing.JTextField();
        txtSexoU = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccionU = new javax.swing.JTextArea();
        cbxTiposUsuarios = new javax.swing.JComboBox<>();
        cbxStatus = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lvlidUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtContraseniaU = new javax.swing.JPasswordField();
        btnCargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Contrasenia", "Nombre", "Apellido Paterno", "Apellido Materno", "Correo Electronico", "Sexo", "Direccion", "Tipo", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTusuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTusuarios);

        jLabel1.setText("Usuario");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        txtUsuarioU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioUKeyTyped(evt);
            }
        });

        jLabel2.setText("Usuario");

        jLabel3.setText("Contrasenia");

        txtNombreU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido Paterno");

        jLabel6.setText("Apellido Materno");

        jLabel7.setText("Correo Electronico");

        jLabel8.setText("Sexo");

        jLabel9.setText("Direccion");

        jLabel10.setText("Tipo Usuario");

        jLabel11.setText("Status");

        txtCorreoU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoUFocusLost(evt);
            }
        });

        txtDireccionU.setColumns(20);
        txtDireccionU.setRows(5);
        jScrollPane2.setViewportView(txtDireccionU);

        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el status" }));

        jLabel12.setText("ID del usuario");

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtContraseniaU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseniaUKeyTyped(evt);
            }
        });

        btnCargar.setText("Cargar Registros");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel12)
                                .addGap(37, 37, 37)
                                .addComponent(lvlidUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuarioU, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(txtNombreU)
                                    .addComponent(txtApU)
                                    .addComponent(txtAmU)
                                    .addComponent(txtContraseniaU))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtCorreoU)
                                    .addComponent(txtSexoU, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxTiposUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCargar)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lvlidUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtUsuarioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtContraseniaU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtAmU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBuscar)
                                        .addComponent(btnCargar))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(15, 15, 15)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(cbxTiposUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSexoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (!txtBuscar.getText().equals("")) {
            sql_usuarios sqlusr = new sql_usuarios();
            String buscarU = new String(txtBuscar.getText());
            if (sqlusr.usuarioExistente(buscarU) == 0) {
                JOptionPane.showMessageDialog(this, "No hay resultados");
            } else {
                if (sqlusr.cargar(this)) {
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Llenar campo para buscar usuario");
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        sql_usuarios sqlusr = new sql_usuarios();
        usuarios urs = new usuarios();

        if (!txtUsuarioU.getText().equals("") && !txtContraseniaU.getText().equals("")
                && !txtNombreU.getText().equals("") && !txtApU.getText().equals("")
                && !txtAmU.getText().equals("") && !txtCorreoU.getText().equals("")
                && !txtSexoU.getText().equals("") && !txtDireccionU.getText().equals("")
                && !cbxTiposUsuarios.getItemAt(cbxTiposUsuarios.getSelectedIndex()).equals("Seleccione tipo de usuario")
                && !cbxStatus.getItemAt(cbxStatus.getSelectedIndex()).equals("Seleccione el status")) {

            String usu = new String(txtUsuarioU.getText());
            String pass = new String(txtContraseniaU.getText());
            String nombre = new String(txtNombreU.getText());
            String ap = new String(txtApU.getText());
            String am = new String(txtAmU.getText());
            String correo = new String(txtCorreoU.getText());
            String sexo = new String(txtSexoU.getText());
            String direccion = new String(txtDireccionU.getText());
            String tipo = cbxTiposUsuarios.getItemAt(cbxTiposUsuarios.getSelectedIndex());
            String status = cbxStatus.getItemAt(cbxStatus.getSelectedIndex());

            if (tipo.equals("Administrador")) {
                tipo = "1";
            } else {
                tipo = "2";
            }

            if (status.equals("Activo")) {
                status = "1";
            } else {
                status = "0";
            }

            int nuevotipo = Integer.parseInt(tipo);
            int nuevoStatus = Integer.parseInt(status);

            if (sqlusr.usuarioExistente(usu) == 0) {
                urs.setUsuario(usu);
                urs.setContrasenia(pass);
                urs.setNombre_usuario(nombre);
                urs.setAp_usuario(ap);
                urs.setAm_usuario(am);
                urs.setCorreo_electronico(correo);
                urs.setSexo(sexo);
                urs.setDireccion(direccion);
                urs.setTipo(nuevotipo);
                urs.setStatus(nuevoStatus);

                if (sqlusr.registrar(urs)) {
                    JOptionPane.showMessageDialog(this, "Usuario Agregado");
                    if (sqlusr.cargar(this)) {
                    }
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al agregar usuario");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Usuario Existente");

            }

        } else {
            JOptionPane.showMessageDialog(this, "Llena todos los campos correctamente");
        }

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtNombreUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUActionPerformed

    private void jTusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTusuariosMouseClicked
        // TODO add your handling code here:
        sql_usuarios sqlusr = new sql_usuarios();

        int fila = jTusuarios.getSelectedRow();
        String id = jTusuarios.getValueAt(fila, 0).toString();

        if (sqlusr.cargaralClic(id, this)) {

        }
    }//GEN-LAST:event_jTusuariosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!lvlidUsuario.equals("")) {
            sql_usuarios sqlusr = new sql_usuarios();
            usuarios urs = new usuarios();

            if (!txtUsuarioU.getText().equals("") && !txtContraseniaU.getText().equals("")
                    && !txtNombreU.getText().equals("") && !txtApU.getText().equals("")
                    && !txtAmU.getText().equals("") && !txtCorreoU.getText().equals("")
                    && !txtSexoU.getText().equals("") && !txtDireccionU.getText().equals("")
                    && !cbxTiposUsuarios.getItemAt(cbxTiposUsuarios.getSelectedIndex()).equals("Seleccione tipo de usuario")
                    && !cbxStatus.getItemAt(cbxStatus.getSelectedIndex()).equals("Seleccione el status")) {

                String usu = new String(txtUsuarioU.getText());
                String pass = new String(txtContraseniaU.getText());
                String nombre = new String(txtNombreU.getText());
                String ap = new String(txtApU.getText());
                String am = new String(txtAmU.getText());
                String correo = new String(txtCorreoU.getText());
                String sexo = new String(txtSexoU.getText());
                String direccion = new String(txtDireccionU.getText());
                String tipo = cbxTiposUsuarios.getItemAt(cbxTiposUsuarios.getSelectedIndex());
                String status = cbxStatus.getItemAt(cbxStatus.getSelectedIndex());
                String id = new String(lvlidUsuario.getText());

                if (tipo.equals("Administrador")) {
                    tipo = "1";
                } else {
                    tipo = "2";
                }

                if (status.equals("Activo")) {
                    status = "1";
                } else {
                    status = "0";
                }

                int nuevotipo = Integer.parseInt(tipo);
                int nuevoStatus = Integer.parseInt(status);
                int nuevoID = Integer.parseInt(id);

                //if (sqlusr.usuarioExistente(usu) == 0) {
                    urs.setUsuario(usu);
                    urs.setContrasenia(pass);
                    urs.setNombre_usuario(nombre);
                    urs.setAp_usuario(ap);
                    urs.setAm_usuario(am);
                    urs.setCorreo_electronico(correo);
                    urs.setSexo(sexo);
                    urs.setDireccion(direccion);
                    urs.setTipo(nuevotipo);
                    urs.setStatus(nuevoStatus);
                    urs.setId_usuario(nuevoID);

                    if (sqlusr.editar(urs)) {
                        JOptionPane.showMessageDialog(this, "Usuario Editado");
                        if (sqlusr.cargar(this)) {
                        }
                        limpiar();
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al editar los datos del usuario");
                    }

                /*} else {
                    JOptionPane.showMessageDialog(this, "Usuario Existente");

                }*/

            } else {
                JOptionPane.showMessageDialog(this, "Llena todos los campos correctamente");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona el usuario a editar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        sql_usuarios sqlusr = new sql_usuarios();
        usuarios urs = new usuarios();
        if (!lvlidUsuario.getText().equals("")) {
            String id = new String(lvlidUsuario.getText());
            int nuevoID = Integer.parseInt(id);

            urs.setId_usuario(nuevoID);

            if (sqlusr.eliminar(urs)) {
                JOptionPane.showMessageDialog(this, "Usuario Eliminado");
                if (sqlusr.cargar(this)) {
                }
                limpiar();
            } else {

            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona el usuario a eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        sql_usuarios sqlusr = new sql_usuarios();
        limpiar();
        if (sqlusr.cargar(this)) {

        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        home.v_usr = null;
    }//GEN-LAST:event_formWindowClosing

    private void txtUsuarioUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioUKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && !Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuarioUKeyTyped

    private void txtContraseniaUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseniaUKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && !Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtContraseniaUKeyTyped

    public boolean isEmail(String correo){
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(correo);
        if(mat.find()){
            return true;
        }else{
            return false;
        }
    }
    
    private void txtCorreoUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoUFocusLost
        // TODO add your handling code here:
        if(isEmail(txtCorreoU.getText())){
            
        }else{
            JOptionPane.showMessageDialog(this, "Correo electronico no valido");
            txtCorreoU.requestFocus();
        }
        
    }//GEN-LAST:event_txtCorreoUFocusLost

    private void limpiar() {
        lvlidUsuario.setText("");
        txtAmU.setText("");
        txtApU.setText("");
        txtBuscar.setText("");
        txtContraseniaU.setText("");
        txtCorreoU.setText("");
        txtDireccionU.setText("");
        txtNombreU.setText("");
        txtSexoU.setText("");
        txtUsuarioU.setText("");
        cbxTiposUsuarios.setSelectedIndex(0);
        cbxStatus.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_usuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_usuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_usuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_usuarios.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCargar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JComboBox<String> cbxStatus;
    public javax.swing.JComboBox<String> cbxTiposUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTusuarios;
    public javax.swing.JLabel lvlidUsuario;
    public javax.swing.JTextField txtAmU;
    public javax.swing.JTextField txtApU;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JPasswordField txtContraseniaU;
    public javax.swing.JTextField txtCorreoU;
    public javax.swing.JTextArea txtDireccionU;
    public javax.swing.JTextField txtNombreU;
    public javax.swing.JTextField txtSexoU;
    public javax.swing.JTextField txtUsuarioU;
    // End of variables declaration//GEN-END:variables
}
