/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.modLogin;
import Modelo.sql_ventas;
import Modelo.ventas;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ettkt
 */
public class vista_ventas extends javax.swing.JFrame {

    modLogin modlog;
    ventas ventas = new ventas();

    sql_ventas sql_vetas = new sql_ventas();

    /**
     * Creates new form vista_ventas
     */
    public vista_ventas() {

        initComponents();
        setLocationRelativeTo(null);

    }

    public vista_ventas(modLogin log) {
        initComponents();
        setLocationRelativeTo(null);
        this.modlog = log;
        lblEmpleado.setText(log.getUsuario());
        lblRol.setText(log.getRol());
        if (sql_vetas.cargar(this)) {
        }
        if (sql_vetas.cargarProd(this)) {
        }
        if (sql_vetas.cargarClientes(this)) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTventas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cbbxProducto = new javax.swing.JComboBox<>();
        txtUnidades = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbbxCliente = new javax.swing.JComboBox<>();
        btnAgregarV = new javax.swing.JButton();
        lbl_cliente = new javax.swing.JLabel();
        lblAp = new javax.swing.JLabel();
        lbl_Am = new javax.swing.JLabel();
        lbl_Direccion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblidVenta = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Unidades", "Empleado", "Cliente", "Fecha", "Cantidad Neto", "Cantidad Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTventasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTventas);

        jLabel1.setText("Empleado");

        jLabel2.setText("Ventas");

        jLabel3.setText("Buscar");

        jButton1.setText("Buscar");

        cbbxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto" }));
        cbbxProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbxProductoItemStateChanged(evt);
            }
        });

        txtUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesActionPerformed(evt);
            }
        });
        txtUnidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnidadesKeyTyped(evt);
            }
        });

        jLabel4.setText("Unidades");

        cbbxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));
        cbbxCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbxClienteItemStateChanged(evt);
            }
        });

        btnAgregarV.setText("Agregar Venta");
        btnAgregarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVActionPerformed(evt);
            }
        });

        jLabel5.setText("Productos");

        jLabel6.setText("Descripcio");

        jLabel7.setText("Precio");

        jLabel8.setText("ID Cliente");

        jLabel9.setText("Nombre");

        jLabel10.setText("Apellido Paterno");

        jLabel11.setText("Apellido Materno");

        jLabel12.setText("Direccion");

        jLabel14.setText("ID venta");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar Venta");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Venta");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(262, 262, 262))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel11))
                                            .addComponent(lblRol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(44, 44, 44))
                                                    .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel12))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Am, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 151, Short.MAX_VALUE))
                                    .addComponent(lbl_Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cbbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addGap(276, 276, 276)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAgregarV)
                                .addComponent(lblidVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                            .addComponent(lbl_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(lbl_Am, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(lbl_Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUnidades, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVActionPerformed
        // TODO add your handling code here:
        if (!lblRol.getText().equals("") && !lblEmpleado.getText().equals("")
                && cbbxProducto.getSelectedIndex() != 0 && !txtUnidades.getText().equals("")
                && cbbxCliente.getSelectedIndex() != 0 /*&& !txtIva.getText().equals("")*/) {

            String codProd = cbbxProducto.getItemAt(cbbxProducto.getSelectedIndex());
            String cantProd = txtUnidades.getText();
            String usuario = lblEmpleado.getText();
            String cliente = cbbxCliente.getItemAt(cbbxCliente.getSelectedIndex());
            String precio = lblPrecio.getText();
            //String impuestoTxt = txtIva.getText();

            int idProd = sql_vetas.obtenerIdProd(codProd);
            int cantidadProd = Integer.parseInt(cantProd);
            int idUsr = sql_vetas.obtenerIdUsuario(usuario);
            int idCliente = Integer.parseInt(cliente);
            double precioProd = Double.parseDouble(precio);
            double total = cantidadProd * precioProd;
            //int impuesto = Integer.parseInt(impuestoTxt);
            //double xctajeImpuesto = cantNeto / 100;
            //double total = xctajeImpuesto + cantNeto;
            System.out.println(idProd);
            System.out.println(cantidadProd);
            System.out.println(idUsr);
            System.out.println(cliente);
            System.out.println(precioProd);
            //System.out.println(cantNeto);
            System.out.println(total);
            int confirmacion = JOptionPane.showConfirmDialog(this, "Confirmar Compra \n "
                    + "Producto: " + codProd + "\n"
                    + "Precio Total: " + total);
            if (confirmacion == 0) {
                ventas.setFk_producto(idProd);
                ventas.setCantidad_producto_vendido(cantidadProd);
                ventas.setFk_usuario(idUsr);
                ventas.setFk_cliente(idCliente);
                //ventas.setCantidad_neto(cantNeto);
                //ventas.setImpuesto_venta(impuesto);
                ventas.setCantidad_total(total);
                //int stock = sql_vetas.stockDisponible(codProd);
                if (sql_vetas.stockDisponible(ventas) >= cantidadProd) {
                    if (sql_vetas.registrar(ventas) && sql_vetas.actualizarStockProd(ventas)) {
                        JOptionPane.showMessageDialog(this, "Venta Realizada");
                        limpiar();
                        if (sql_vetas.cargar(this)) {
                        }
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al agregar venta");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No hay suficientes unidades");
                }
            } else if (confirmacion == 1) {
            } else {
                limpiar();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Llena los campos correctamente");
        }
    }//GEN-LAST:event_btnAgregarVActionPerformed

    private void txtUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesActionPerformed

    private void txtUnidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadesKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        int tam = txtUnidades.getText().length();
        if (!Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE || (c == KeyEvent.VK_DELETE))
                || tam >2) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUnidadesKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        home.vv = null;
    }//GEN-LAST:event_formWindowClosing

    private void cbbxClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbxClienteItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cbbxCliente.getSelectedIndex() == 0) {
                lbl_cliente.setText("");
                lblAp.setText("");
                lbl_Am.setText("");
                lbl_Direccion.setText("");
            } else {
                String id = cbbxCliente.getItemAt(cbbxCliente.getSelectedIndex());
                if (sql_vetas.ontenerDatosCliente(id, this)) {
                }
            }
        }
    }//GEN-LAST:event_cbbxClienteItemStateChanged

    private void cbbxProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbxProductoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cbbxProducto.getSelectedIndex() == 0) {
                lblDescripcion.setText("");
                lblPrecio.setText("");
            } else {
                String codigoProd = cbbxProducto.getItemAt(cbbxProducto.getSelectedIndex());
                if (sql_vetas.obtenerDatosProductos(codigoProd, this)) {
                }
            }
        }
    }//GEN-LAST:event_cbbxProductoItemStateChanged

    private void jTventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTventasMouseClicked
        // TODO add your handling code here:
        int fila = jTventas.getSelectedRow();
        String id = jTventas.getValueAt(fila, 0).toString();
        lblidVenta.setText(id);
        int idvnta = Integer.parseInt(id);
        cbbxProducto.setSelectedItem(jTventas.getValueAt(fila, 1).toString());
        txtUnidades.setText(jTventas.getValueAt(fila, 3).toString());
        String nom_usr = jTventas.getValueAt(fila, 5).toString();
        int idUsr = sql_vetas.obtenerIDusr(nom_usr);
        String idC = Integer.toString(idUsr);
        cbbxCliente.setSelectedItem(idC);
        int impuesto = sql_vetas.obtenerImpuestoVnta(idvnta);
        /*String impuestoVnta = Integer.toString(impuesto);
        txtIva.setText(impuestoVnta);
        
        int fila = jTproductos.getSelectedRow();
        lvlid.setText(jTproductos.getValueAt(fila, 0).toString());
        txtCodigo.setText(jTproductos.getValueAt(fila, 1).toString());
        txtDescripcion.setText(jTproductos.getValueAt(fila, 2).toString());
        cbbxCategorias.setSelectedItem(jTproductos.getValueAt(fila, 3).toString());
         */
    }//GEN-LAST:event_jTventasMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (!lblidVenta.getText().equals("")) {

            if (!lblRol.getText().equals("") && !lblEmpleado.getText().equals("")
                    && cbbxProducto.getSelectedIndex() != 0 && !txtUnidades.getText().equals("")
                    && cbbxCliente.getSelectedIndex() != 0 /*&& !txtIva.getText().equals("")*/) {

                String codProd = cbbxProducto.getItemAt(cbbxProducto.getSelectedIndex());
                String cantProd = txtUnidades.getText();
                String usuario = lblEmpleado.getText();
                String cliente = cbbxCliente.getItemAt(cbbxCliente.getSelectedIndex());
                String precio = lblPrecio.getText();
                //String impuestoTxt = txtIva.getText();
                String idVenta = lblidVenta.getText();

                int idProd = sql_vetas.obtenerIdProd(codProd);
                int cantidadProd = Integer.parseInt(cantProd);
                int idUsr = sql_vetas.obtenerIdUsuario(usuario);
                int idCliente = Integer.parseInt(cliente);
                double precioProd = Double.parseDouble(precio);
                double cantNeto = cantidadProd * precioProd;
                //int impuesto = Integer.parseInt(impuestoTxt);
                double xctajeImpuesto = cantNeto / 100;
                double total = xctajeImpuesto + cantNeto;
                int idVnta = Integer.parseInt(idVenta);
                /*System.out.println(idProd);
            System.out.println(cantidadProd);
            System.out.println(idUsr);
            System.out.println(cliente);
            System.out.println(precioProd);
            System.out.println(cantNeto);
            System.out.println(total);*/
                int confirmacion = JOptionPane.showConfirmDialog(this, "Confirmar Modificacion de venta? \n "
                        + "Producto: " + codProd + "\n"
                        + "Precio Neto: " + precioProd + "\n"
                        + "Precio Total: " + total);
                if (confirmacion == 0) {
                    ventas.setFk_producto(idProd);
                    ventas.setCantidad_producto_vendido(cantidadProd);
                    ventas.setFk_usuario(idUsr);
                    ventas.setFk_cliente(idCliente);
                    ventas.setCantidad_neto(cantNeto);
                    //ventas.setImpuesto_venta(impuesto);
                    ventas.setCantidad_total(total);
                    ventas.setId_venta(idVnta);
                    //int stock = sql_vetas.stockDisponible(codProd);
                    if (sql_vetas.stockDisponible(ventas) >= cantidadProd) {
                        if (sql_vetas.editar(ventas) && sql_vetas.actualizarStockProd(ventas)) {
                            JOptionPane.showMessageDialog(this, "Venta Editada");
                            limpiar();
                            if (sql_vetas.cargar(this)) {
                            }
                            /*if (sql_vetas.cargarClientes(this)) {
                            }
                            if (sql_vetas.cargarProd(this)) {
                            }*/
                        } else {
                            JOptionPane.showMessageDialog(this, "Error al agregar venta");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "No hay suficientes unidades");
                    }
                } else if (confirmacion == 1) {
                } else {
                    limpiar();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Llena los campos correctamente");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecciona la venta para editar");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (!lblidVenta.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "Confirmar la eliminacion de la venta? \n ");
            if (confirmacion == 0) {
                String idVenta = lblidVenta.getText();
                int idVnta = Integer.parseInt(idVenta);
                ventas.setId_venta(idVnta);
                if(sql_vetas.eliminar(ventas)){
                    sql_vetas.cargar(this);
                    limpiar();
                }
            } else if (confirmacion == 1) {
            } else {
                limpiar();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona la venta para editar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    public void limpiar() {
        lblidVenta.setText("");
        cbbxProducto.setSelectedIndex(0);
        txtUnidades.setText("");
        //txtIva.setText("");
        cbbxCliente.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarV;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JComboBox<String> cbbxCliente;
    public javax.swing.JComboBox<String> cbbxProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTable jTventas;
    public javax.swing.JLabel lblAp;
    public javax.swing.JLabel lblDescripcion;
    public javax.swing.JLabel lblEmpleado;
    public javax.swing.JLabel lblPrecio;
    public javax.swing.JLabel lblRol;
    public javax.swing.JLabel lbl_Am;
    public javax.swing.JLabel lbl_Direccion;
    public javax.swing.JLabel lbl_cliente;
    public javax.swing.JLabel lblidVenta;
    public javax.swing.JTextField txtUnidades;
    // End of variables declaration//GEN-END:variables
}
